/**
 * RegKit AGENT-5 — Evidence Compiler
 *
 * Takes the findings from a scan (deterministic detectors + optional
 * AGENT-3 reasoning) and compiles them into the compliance documents that
 * regulators, auditors, and enterprise procurement teams demand.
 *
 * This is the commercial engine of RegKit: a compliance officer producing
 * these manually spends weeks per document. AGENT-5 generates the draft as
 * a byproduct of a scan that already happened.
 *
 * MVP scope — generates the two documents fed by the most rules, both
 * highly auto-generatable:
 *   1. AI System Data Flow Diagram (fed by 10 of 13 rules) — 100% auto
 *   2. Algorithmic Impact Assessment (fed by 5 rules) — ~60% auto, marks
 *      the human-completion sections explicitly
 *
 * Each rule's YAML `evidence_contribution` block declares which document
 * it feeds and which section — so the generated documents are assembled
 * from the same statutory research that produced the rules, not invented.
 *
 * Output is Markdown (renders on GitHub, converts cleanly to PDF later via
 * the same Puppeteer path described in the playbook). No paid API needed —
 * document generation is deterministic assembly of scan results.
 */

// ─── SHARED HELPERS ───────────────────────────────────────────────────────────

function todayISO() {
  return new Date().toISOString().slice(0, 10);
}

/** Groups findings by the document(s) their rule contributes to */
function indexFindingsByDocument(findings, ruleMap) {
  const byDoc = {};
  for (const finding of findings) {
    const rule = ruleMap[finding.ruleId];
    if (!rule) continue;
    const contributions = rule.evidence_contribution || [];
    for (const c of contributions) {
      const doc = c.document;
      if (!doc) continue;
      if (!byDoc[doc]) byDoc[doc] = [];
      byDoc[doc].push({ finding, rule, section: c.section || 'General', note: c.note });
    }
  }
  return byDoc;
}

/** A small banner every generated document carries — RegKit is not a law firm */
const DISCLAIMER =
  '> **Disclaimer:** This document was auto-generated by RegKit from a static + reasoning scan of source code. ' +
  'It is a compliance-intelligence draft, not legal advice, and not a substitute for review by qualified legal counsel. ' +
  'Sections marked _[HUMAN COMPLETION REQUIRED]_ contain determinations RegKit cannot make from code alone.';

// ─── DOCUMENT 1: AI SYSTEM DATA FLOW DIAGRAM ──────────────────────────────────
// Fed by 10 rules. 100% auto-generatable: it describes what data flows where,
// derived entirely from the scan. Rendered as a Mermaid diagram (GitHub-native)
// plus a tabular inventory.

function generateDataFlowDiagram(findings, ruleMap, projectConfig, scanMeta) {
  const projectName = (projectConfig.project && projectConfig.project.name) || projectConfig.name || 'Unnamed Project';

  // Collect the AI touchpoints from findings: function name + vendor/media + data signals
  const touchpoints = [];
  const seen = new Set();
  for (const f of findings) {
    const key = `${f.file}:${f.functionName}`;
    if (seen.has(key)) continue;
    seen.add(key);
    touchpoints.push({
      fn: f.functionName,
      file: f.file,
      vendor: f.vendor || inferVendorFromSnippet(f.codeSnippet),
      sensitive: inferSensitivityFromFindings(findings, f.functionName),
      line: f.line,
    });
  }

  let md = `# AI System Data Flow Diagram\n\n`;
  md += `**Project:** ${projectName}  \n`;
  md += `**Generated:** ${todayISO()} by RegKit AGENT-5  \n`;
  md += `**Source:** automated scan of ${scanMeta.fileCount} file(s)  \n\n`;
  md += DISCLAIMER + '\n\n';
  md += `## Purpose\n\nThis diagram maps every point where this codebase sends data to an AI model, what kind of data flows through each point, and which compliance obligations attach. It satisfies the first question every regulator, auditor, and enterprise security team asks: *what data goes into your AI, and where does the output go?*\n\n`;
  md += `It is referenced by EU AI Act Art. 10 (data governance), HIPAA audit investigations, SOC 2 CC6.6, and enterprise security questionnaires.\n\n`;

  // Mermaid diagram
  md += `## Flow Diagram\n\n\`\`\`mermaid\nflowchart LR\n`;
  if (touchpoints.length === 0) {
    md += `  NoAI["No AI touchpoints detected in scan"]\n`;
  } else {
    touchpoints.forEach((t, i) => {
      const dataLabel = t.sensitive.length ? t.sensitive.join(', ') : 'application data';
      const vendorLabel = t.vendor || 'AI model';
      md += `  IN${i}["${dataLabel}"] --> FN${i}["${t.fn}()"]\n`;
      md += `  FN${i} -->|sends to| AI${i}["${vendorLabel}"]\n`;
      md += `  AI${i} -->|output| OUT${i}["downstream action"]\n`;
    });
  }
  md += `\`\`\`\n\n`;

  // Tabular inventory
  md += `## Data Flow Inventory\n\n`;
  md += `| AI Touchpoint | Location | Vendor / Model | Data Sensitivity | Line |\n`;
  md += `|---|---|---|---|---|\n`;
  if (touchpoints.length === 0) {
    md += `| _none detected_ | — | — | — | — |\n`;
  } else {
    for (const t of touchpoints) {
      const sens = t.sensitive.length ? '⚠️ ' + t.sensitive.join(', ') : 'standard';
      md += `| \`${t.fn}()\` | ${shortPath(t.file)} | ${t.vendor || 'unspecified'} | ${sens} | ${t.line} |\n`;
    }
  }
  md += `\n`;

  // Obligations attached, pulled from the rules that fired
  md += `## Compliance Obligations Attached to These Flows\n\n`;
  const obligations = collectObligations(findings, ruleMap, 'AI System Data Flow Diagram');
  if (obligations.length === 0) {
    md += `_No flagged obligations for these flows in this scan._\n`;
  } else {
    for (const o of obligations) {
      md += `- **${o.framework}** (${o.citation}) — ${o.section}\n`;
    }
  }
  md += `\n`;

  return md;
}

// ─── DOCUMENT 2: ALGORITHMIC IMPACT ASSESSMENT ────────────────────────────────
// Fed by 5 rules. ~60% auto: RegKit fills system description, data sources,
// and obligation tracking; explicitly marks the bias-testing-results and
// sign-off sections as requiring human completion.

function generateAlgorithmicImpactAssessment(findings, ruleMap, projectConfig, scanMeta) {
  const projectName = (projectConfig.project && projectConfig.project.name) || projectConfig.name || 'Unnamed Project';
  const jurisdictions = (projectConfig.project && projectConfig.project.jurisdictions) || projectConfig.jurisdictions || ['unspecified'];

  let md = `# Algorithmic Impact Assessment\n\n`;
  md += `**Project:** ${projectName}  \n`;
  md += `**Jurisdictions in scope:** ${jurisdictions.join(', ')}  \n`;
  md += `**Generated:** ${todayISO()} by RegKit AGENT-5  \n\n`;
  md += DISCLAIMER + '\n\n';

  md += `## 1. System Description _(auto-generated)_\n\n`;
  const aiFunctions = [...new Set(findings.map(f => f.functionName))];
  if (aiFunctions.length) {
    md += `This codebase contains ${aiFunctions.length} AI-assisted decision or generation function(s) in regulatory scope:\n\n`;
    for (const fn of aiFunctions) md += `- \`${fn}()\`\n`;
  } else {
    md += `No AI decision functions in regulatory scope were detected in this scan.\n`;
  }
  md += `\n`;

  md += `## 2. Data Sources & Protected-Characteristic Proxies _(auto-generated)_\n\n`;
  const proxyFindings = findings.filter(f => /zip|proxy|biometric|phi/i.test(JSON.stringify(f)));
  if (proxyFindings.length) {
    md += `RegKit detected the following sensitive-data or proxy-variable signals:\n\n`;
    for (const f of proxyFindings) {
      md += `- In \`${f.functionName}()\`: ${f.detail || f.ruleName}\n`;
    }
  } else {
    md += `No protected-characteristic proxy variables detected in this scan.\n`;
  }
  md += `\n`;

  md += `## 3. Obligations by Jurisdiction _(auto-generated)_\n\n`;
  const aiaObligations = collectObligations(findings, ruleMap, 'Algorithmic Impact Assessment');
  if (aiaObligations.length) {
    md += `| Framework | Citation | Obligation tracked |\n|---|---|---|\n`;
    for (const o of aiaObligations) {
      md += `| ${o.framework} | ${o.citation} | ${o.section} |\n`;
    }
  } else {
    md += `_No Algorithmic-Impact-Assessment obligations flagged in this scan._\n`;
  }
  md += `\n`;

  md += `## 4. Bias Testing Methodology & Results _[HUMAN COMPLETION REQUIRED]_\n\n`;
  md += `RegKit cannot run a statistical disparate-impact analysis from source code — that requires actual outcome data across real decisions. The bias audit must be completed by a qualified party (and, for NYC Local Law 144, an *independent* auditor) and its results recorded here.\n\n`;
  md += `- [ ] Testing methodology documented\n- [ ] Selection rates / impact ratios by protected class\n- [ ] Four-fifths rule analysis (where applicable)\n- [ ] Independent auditor engaged (required for NYC LL144)\n\n`;

  md += `## 5. Mitigation Measures _[HUMAN COMPLETION REQUIRED]_\n\n`;
  md += `- [ ] Measures taken in response to identified risks\n- [ ] Residual risk acceptance and rationale\n\n`;

  md += `## 6. Responsible Officer Sign-off _[HUMAN COMPLETION REQUIRED]_\n\n`;
  md += `- Name: ____________________\n- Title: ____________________\n- Date: ____________________\n- Signature: ____________________\n\n`;

  return md;
}

// ─── HELPERS ──────────────────────────────────────────────────────────────────

function inferVendorFromSnippet(snippet) {
  if (!snippet) return null;
  if (/openai/i.test(snippet)) return 'OpenAI';
  if (/anthropic/i.test(snippet)) return 'Anthropic';
  if (/imageGen|dall|diffusion/i.test(snippet)) return 'Image-gen model';
  if (/mlModel|\.predict|\.score/i.test(snippet)) return 'Internal ML model';
  if (/llm\.complete/i.test(snippet)) return 'LLM';
  return null;
}

function inferSensitivityFromFindings(findings, fnName) {
  const sens = new Set();
  for (const f of findings) {
    if (f.functionName !== fnName) continue;
    const blob = (f.detail || '') + ' ' + (f.ruleName || '');
    if (/PHI|health/i.test(blob)) sens.add('PHI');
    if (/biometric/i.test(blob)) sens.add('biometric');
    if (/credit|loan|adverse action/i.test(blob)) sens.add('credit data');
    if (/zip code|proxy/i.test(blob)) sens.add('protected-class proxy');
    if (/employment|hiring|AEDT/i.test(blob)) sens.add('employment data');
  }
  return [...sens];
}

function collectObligations(findings, ruleMap, docName) {
  const out = [];
  const seen = new Set();
  for (const f of findings) {
    const rule = ruleMap[f.ruleId];
    if (!rule) continue;
    const contribs = rule.evidence_contribution || [];
    for (const c of contribs) {
      if (c.document !== docName) continue;
      const reg = rule.regulation || {};
      const key = rule.id + c.section;
      if (seen.has(key)) continue;
      seen.add(key);
      out.push({
        framework: reg.framework || rule.id,
        citation: reg.citation || 'n/a',
        section: c.section || 'General',
      });
    }
  }
  return out;
}

function shortPath(p) {
  const parts = p.split('/');
  return parts.slice(-2).join('/');
}

// ─── PUBLIC INTERFACE ─────────────────────────────────────────────────────────

const GENERATORS = {
  'data-flow-diagram': {
    title: 'AI System Data Flow Diagram',
    fn: generateDataFlowDiagram,
    filename: 'AI-System-Data-Flow-Diagram.md',
  },
  'impact-assessment': {
    title: 'Algorithmic Impact Assessment',
    fn: generateAlgorithmicImpactAssessment,
    filename: 'Algorithmic-Impact-Assessment.md',
  },
};

/**
 * Generates one or more evidence documents from scan findings.
 * @returns array of { docType, title, filename, markdown }
 */
function generateEvidence(docTypes, findings, ruleMap, projectConfig, scanMeta) {
  const which = (docTypes && docTypes.length) ? docTypes : Object.keys(GENERATORS);
  const out = [];
  for (const key of which) {
    const gen = GENERATORS[key];
    if (!gen) continue;
    const markdown = gen.fn(findings, ruleMap, projectConfig, scanMeta);
    out.push({ docType: key, title: gen.title, filename: gen.filename, markdown });
  }
  return out;
}

module.exports = {
  generateEvidence,
  GENERATORS,
  indexFindingsByDocument,
};
